name: "Continuous Integration"
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*.*.*
  pull_request:
    types: [opened, synchronize, reopened]
env:
  NODE_VERSION: "18.12.1"
jobs:
  ci:
    name: Continuous Integration
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install
        run: |
          npm ci

      - name: typecheck
        run: |
          npm run typecheck

      - name: test
        run: |
          npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
